steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'services'
      - 'enable'
      - 'cloudfunctions.googleapis.com'
      - '--project=$_TARGET_PROJECT_ID'

  # Enable Cloud Build API as required to deploy Cloud Functions.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'services'
      - 'enable'
      - 'cloudbuild.googleapis.com'
      - '--project=$_TARGET_PROJECT_ID'

  # Deploy the Cloud Function using Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - $_FUNCTION_NAME
      - '--runtime=nodejs20'
      - '--trigger-topic=${_TRIGGER_TOPIC}'
      - '--entry-point=send'
      - '--service-account=${_ACCOUNT_NAME}@${_TARGET_PROJECT_ID}.iam.gserviceaccount.com'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars=OVERRIDE_TO=${_OVERRIDE_TO}'
      - '--project=$_TARGET_PROJECT_ID'

substitutions:
  _TARGET_PROJECT_ID: '$PROJECT_ID'
  _FUNCTION_NAME: sms
  _ACCOUNT_NAME: 'sms'
  _REGION: '$LOCATION'
  _TRIGGER_TOPIC: sms
  _OVERRIDE_TO: ''

timeout: 1200s


options:
  dynamicSubstitutions: true
